service: scrapper-lambda
provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline
  - serverless-plugin-chrome
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  hello:
    handler: handler.hello
    memorySize: 2048MB
    timeout: 60
    events:
      - http:
          path: /
          method: get
